예외처리
- 예외란 문법적 문제가 아닌 프로그램을 실행하며 비정상적으로 발생하는 문제상황이다. 단순 코딩의 문제는 예외가 아닌 오류이다.
- 자바는 예외 상황이 발생했을때 원인은 알지만 어떻게 처리해야하는지는 모르기 때문에 프로그램을 단순 종료한다.
- 예외처리는 예외가 발생했을때 프로그램이 종료되지 않도록 하기 위해 사용한다.
- 예외처리는 try-catch문을 사용한다.
- 예외가 발생하는 상황에서 출력된 메세지를 통해 어떤 예외가 발생한 것인지 알 수 있다.
- ArithmeticException : 수학 연산에서 오류값이 발생할때 발생하는 예외
- InputMismatchException : 입력값이 잘못되었을때 발생하는 예외
- ArrayIndexOutOfBoundsException : 배열의 인덱스 범위를 벗어날때 발생하는 예외
- try-catch문을 사용할 때는 try부분에 예외가 발생할 수 있는 코드를 작성하고 catch부분에 예외가 발생했을때 처리할 코드를 작성한다.
- try영역을 실행하던 도중 예외상황이 발생하면 가상머신은 해당 오류를 인스턴스화하여 힙메모리에 저장한다. 이때 저장된 인스턴스는 catch구문의 매개변수 e로 전달된다.
- catch구문은 여러개 사용할 수 있으며 여러개의 예외를 처리할 수 있다.
- 여러개의 catch구문을 사용할 때 catch를 여러개 사용하지 않고 |를 사용하여 여러개의 예외를 처리할 수 있다.

<br>

- 자바에서 예외클래스의 최상위 클래스는 Throwable클래스이다. 이 클래스에는 발생한 예외의 정보를 알 수 있는 메소드가 있고, public String getmessage()를 통해 예외 원인 문자열을 반환하거나 public void printStackTrace()를 통해 예외가 발생한 위치와 호출된 메소드 정보를 출력할 수 있다.
- 예외처리를 하지 않으면 프로그램이 종료되기 때문에 예외처리를 해주어야 한다.

<br>

![](20250328104837.png)

![](20250328105154.png)

- store는 coffee를 가진다. = new 해서 메모리에 저장한다(has관계)
- store는 guest에게 coffee를 주문 받으면 판매한다. > guest가 가지고 있는 money를 받고, store는 가지고 있던 coffee를 전달한다 (guest와 store를 연결할 때 호출하면 됨. guest가 store에 가서 커피를 구매하는 것이기 때문에 guest의 buyCoffee 메소드에서 store를 호출한다.)

![](20250328105501.png)

- guest는 기본적으로 돈을 가진 상태이다.
- this는 자기 자신을 참조하는 메소드이다.

<br>

[과제]<br>
잠실 롯데 엘리베이터를 타려는 사람이 자신이 원하는 층에 내리도록 만들기
- 1층부터 100층까지 올라갑니다.
- 10명의 사람이 원하는 층에 내립니다.(원하는 층은 랜덤)

클래스 : 엘리베이터, 사람
